import { StyleSheet } from 'react-native';
import { colors } from '../../common/constants/colors.constants';

export const s = StyleSheet.create({
  heroCopy: { gap: 16 },
  sourceCopy: { flex: 1, gap: 6 },
  flexCopy: { flex: 1, gap: 8 },
  stackArt: { width: 66, height: 76 },
  stackLayer: {
    position: 'absolute',
    width: 50,
    height: 48,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.purple,
  },
  footer: { textAlign: 'center' },
  savedText: { color: colors.lime },
  playerTitle: { fontSize: 38 },
  trackRow: {
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderColor: colors.line,
  },
  trackName: { flex: 1, fontSize: 16 },
  progressOrbit: {
    width: 100,
    height: 100,
    borderRadius: 50,
    borderWidth: 2,
    borderColor: colors.lime,
    alignItems: 'center',
    justifyContent: 'center',
  },
  progressRing: {
    width: 68,
    height: 68,
    borderRadius: 34,
    borderWidth: 12,
    borderColor: colors.purple,
  },
  progressDot: {
    position: 'absolute',
    left: 40,
    top: -10,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: colors.lime,
  },
  root: { flex: 1, backgroundColor: colors.bg },
  page: {
    padding: 24,
    paddingTop: 18,
    paddingBottom: 44,
    gap: 24,
    width: '100%',
    maxWidth: 720,
    alignSelf: 'center',
  },
  nav: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  logo: {
    color: colors.text,
    fontSize: 20,
    fontWeight: '900',
    letterSpacing: -0.7,
  },
  badge: {
    color: colors.lime,
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1.5,
  },
  heading: { gap: 10 },
  eyebrow: {
    color: colors.lime,
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 2,
  },
  title: {
    color: colors.text,
    fontSize: 34,
    lineHeight: 38,
    fontWeight: '800',
    letterSpacing: -1.3,
  },
  heroTitle: {
    color: colors.text,
    fontSize: 54,
    lineHeight: 55,
    fontWeight: '800',
    letterSpacing: -2.8,
  },
  body: { color: colors.muted, fontSize: 14, lineHeight: 22 },
  light: { color: colors.text },
  dark: { color: colors.bg },
  row: { flexDirection: 'row', alignItems: 'center', gap: 14 },
  wrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  panel: {
    backgroundColor: colors.panel,
    borderRadius: 24,
    padding: 20,
    gap: 16,
    borderWidth: 1,
    borderColor: colors.line,
  },
  sectionTitle: {
    color: colors.text,
    fontSize: 20,
    fontWeight: '700',
    letterSpacing: -0.5,
  },
  sectionNumber: { color: colors.muted, fontSize: 12, fontWeight: '600' },
  button: {
    minHeight: 50,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 14,
    borderRadius: 15,
    backgroundColor: colors.lime,
  },
  secondary: { backgroundColor: '#303237' },
  buttonText: { color: colors.bg, fontWeight: '800', fontSize: 14 },
  pressed: { opacity: 0.72, transform: [{ scale: 0.98 }] },
  chip: {
    minHeight: 44,
    justifyContent: 'center',
    paddingHorizontal: 15,
    borderRadius: 22,
    backgroundColor: '#292B30',
    borderWidth: 1,
    borderColor: colors.line,
  },
  chipSelected: { backgroundColor: colors.lime, borderColor: colors.lime },
  chipText: { color: colors.muted, fontSize: 12, fontWeight: '700' },
  centerModal: {
    ...StyleSheet.absoluteFill,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  card: {
    width: '100%',
    maxWidth: 480,
    padding: 24,
    borderRadius: 28,
    backgroundColor: colors.panel,
    borderWidth: 1,
    borderColor: colors.line,
    gap: 20,
  },
  sheetModal: { ...StyleSheet.absoluteFill, justifyContent: 'flex-end' },
  sheet: {
    width: '100%',
    maxWidth: 720,
    alignSelf: 'center',
    maxHeight: '90%',
    padding: 24,
    paddingBottom: 36,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    backgroundColor: colors.panel,
    gap: 20,
  },
  handle: {
    width: 38,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#64665F',
    alignSelf: 'center',
  },
  art: {
    overflow: 'hidden',
    borderRadius: '19.230769%',
    backgroundColor: '#F07847',
    alignItems: 'center',
    justifyContent: 'center',
  },
  artFill: StyleSheet.absoluteFill,
  orbit: {
    position: 'absolute',
    borderRadius: '50%',
    backgroundColor: '#D1BEFC',
    transform: [{ rotateZ: '-25deg' }],
  },
  orbitCutout: {
    position: 'absolute',
    borderRadius: '50%',
    backgroundColor: '#F07847',
  },
  artDot: {
    position: 'absolute',
    width: '12%',
    height: '12%',
    borderRadius: 999,
    top: '19%',
    right: '20%',
    backgroundColor: colors.lime,
  },
  caption: { color: colors.muted, fontSize: 11, lineHeight: 17 },
  trackTitle: {
    color: colors.text,
    fontSize: 26,
    fontWeight: '800',
    letterSpacing: -0.8,
  },
  centered: { alignItems: 'center', gap: 20 },
  progressTrack: {
    height: 5,
    borderRadius: 3,
    overflow: 'hidden',
    backgroundColor: colors.line,
    width: '100%',
  },
  progressFill: {
    height: '100%',
    width: '100%',
    backgroundColor: colors.lime,
    transformOrigin: 'left',
  },
});
